version: "3.8"
# Define services
services:
  beauty-salon-server:
    # Configuration for building the docker image for the backend service
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - dbpostgres
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbpostgres:5432/simpledb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend
  front:
    build:
      context: ../front # Use an image built from the specified dockerfile in the `polling-app-client` directory.
      dockerfile: Dockerfile
      args:.
        REACT_APP_API_BASE_URL: http://127.0.0.1:8080/api
    ports:
      - 9090:80 # Map the exposed port 80 on the container to port 9090 on the host machine
    restart: always
    depends_on:
      - beauty-salon-server
    networks:
      - frontend
  dbpostgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - backend
# Volumes
volumes:
  db-data:
networks:
  backend:
  frontend:
